project:
  type: website
  output-dir: docs
  render:
    - 01_axcessr_conceptualisation.qmd
    - 02_axcessr_data_validity.qmd
    - 03_axcessr_ux_research.qmd

execute:
  freeze: auto


website:
  title: "AXCESSR Showcase"
  sidebar:
    style: "floating"
    search: false
    contents:
      - text: "1) Conceptualisation"
        href: 01_axcessr_conceptualisation.html
      - text: "2) Data Validity"
        href: 02_axcessr_data_validity.html
      - text: "3) UX Research"
        href: 03_axcessr_ux_research.html

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true