project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - 01_axcessr_conceptualisation.qmd
    - 02_axcessr_data_validity.qmd
    - 03_axcessr_ux_research.qmd

execute:
  freeze: auto

website:
  title: "AXCESSR Showcase"
  navbar:
    left:
      - text: "Conceptualisation"
        href: 01_axcessr_conceptualisation.html
      - text: "Data Validity"
        href: 02_axcessr_data_validity.html
      - text: "UX Research"
        href: 03_axcessr_ux_research.html


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true